# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('document', models.FileField(upload_to='archive/', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0410\u0440\u0445\u0438\u0432',
                'verbose_name_plural': '\u0410\u0440\u0445\u0438\u0432',
            },
        ),
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ('order',), 'verbose_name': '\u0421\u043c\u0435\u0442\u0430', 'verbose_name_plural': '\u0421\u043c\u0435\u0442\u0430'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='execution',
            field=models.FileField(blank=True, upload_to='estimate/', verbose_name='\u0418\u0441\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435'),
        ),
    ]
